version: 2
updates:
    - package-ecosystem: 'gomod'
      directory: './server'
      schedule:
          interval: 'daily'
          time: '19:00' # UTC(+5)
      commit-message:
          prefix: 'chore'
          include: 'scope'
      open-pull-requests-limit: 7
