linters:
    disable-all: true
    enable:
        - unused
        - gocyclo
        - goconst
        - interfacebloat
        - unconvert
        - gofmt
        - govet
        - errcheck
        - staticcheck
        - gosimple
        - ineffassign

run:
    deadline: 10m

issues:
    exclude-rules:
        - path: _test\.go
          linters:
              - errcheck

# Настройки для конкретных линтеров
linters-settings:
    golint:
        min-confidence: 0
    gocyclo:
        min-complexity: 15
