name: Build User MicroService

on:
    push:
        branches: [main]
        paths:
            - 'server/user-service/**'
    pull_request:
        branches: [main]
        paths:
            - 'server/user-service/**'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
            issues: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: '1.23.0'

            - name: Change directory
              working-directory: ./server/user-service
              run: pwd

            - name: Install dependencies
              working-directory: ./server/user-service
              run: |
                  go mod download

            - name: Run make
              working-directory: ./server/user-service
              run: make build

            - name: Archive artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: user-service
                  path: ./server/user-service/bin/user-service
